- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'AzureRM'
    appType: 'webAppLinux'
    WebAppName: 'pytempmarkov'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'