trigger:
- master

pool:
  name: Hosted Ubuntu 1604


steps:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'AzureRM'
    appType: 'webAppLinux'
    WebAppName: 'pytempmarkov'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'